spring:
  application:
    name: netloan-cred-web-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true
      ribbon:
        enabled: true 
server:
  port: 9093
######没有采用Feign，RestTempate + Ribbon 无法实现超时设置，加上hystrix实现熔断
#ribbon:
#  ReadTimeout: 2000
#  SocketTimeout: 2000 
####此方法设置无效########################
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试当ribbon超时后且hystrix没有超时，便会采取重试机制。
hystrix:
  command:
    remote: 
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  client:
    service-url: 
       defaultZone : http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka