spring:
  application:
    name: netloan-moniter
server:
  port: 9097
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
logging:
  file:
    path: ./logs